// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_QRN96vUgECnavhG49s72onPHlfP1p2E',
    appId: '1:1077465483857:web:dc70eb4d7a1e1c300ec670',
    messagingSenderId: '1077465483857',
    projectId: 'fir-project-c4822',
    authDomain: 'fir-project-c4822.firebaseapp.com',
    storageBucket: 'fir-project-c4822.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoiBfsG46GpBuK3LcHx8bxpT7NdvlnBPA',
    appId: '1:1077465483857:android:992ac8701bafacaa0ec670',
    messagingSenderId: '1077465483857',
    projectId: 'fir-project-c4822',
    storageBucket: 'fir-project-c4822.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvalANniCkKBctyith1MyQDv9kjM2C7r0',
    appId: '1:1077465483857:ios:c5151937dc07dc7f0ec670',
    messagingSenderId: '1077465483857',
    projectId: 'fir-project-c4822',
    storageBucket: 'fir-project-c4822.appspot.com',
    iosBundleId: 'com.example.firebase',
  );
}
